# Generated by Django 5.1.15 on 2026-09-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='SNABTASH B2B', max_length=255)),
                ('phone_1', models.CharField(default='+998 87 034 97 79', max_length=50)),
                ('phone_2', models.CharField(default='+998 90 123 45 67', max_length=50)),
                ('email', models.EmailField(default='info@snabtash.uz', max_length=254)),
                ('telegram_bot', models.CharField(default='@snabtash_bot', max_length=100)),
                ('telegram_channel', models.CharField(default='https://t.me/snabtash', max_length=255)),
                ('address', models.TextField(default='Toshkent sh., Chilonzor tumani, Bunyodkor shox ko‘chasi, 42-uy')),
                ('work_hours', models.CharField(default='Dush - Shan: 08:30 - 18:30', max_length=100)),
                ('inn', models.CharField(default='309871234', max_length=50)),
                ('mfo', models.CharField(default='00440', max_length=50)),
                ('bank_account', models.CharField(default='20208000900123456001', max_length=100)),
                ('bank_name', models.CharField(default='ATB "Kapitalbank" Chilonzor filiali', max_length=255)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=500000, max_digits=14)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=35000, max_digits=14)),
                ('banner_headline', models.CharField(default='Korxonangiz Uchun Barcha Ta’minot', max_length=255)),
                ('banner_subtitle', models.TextField(default='Ishingiz uchun sifatli klining kimyolari, xo‘jalik mollari va gigiyena tovarlarini to‘g‘ridan-to‘g‘ri ombordan oling.')),
                ('banner_discount_badge', models.CharField(default='Maxsus B2B Taklif • 20% Chegirma', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
