# Generated by Django 5.1.15 on 2026-09-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='KORXONALAR UCHUN', max_length=100, verbose_name='Badge')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('btn_text', models.CharField(default='Katalogni ko‘rish', max_length=100, verbose_name='Tugma matni')),
                ('btn_link', models.CharField(default='/catalog', max_length=255, verbose_name='Tugma havolasi')),
                ('image', models.CharField(default='/hero-supply-pack.jpg', max_length=500, verbose_name='Rasm URL')),
                ('image_alt', models.CharField(blank=True, default='', max_length=255, verbose_name='Rasm tavsifi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
