# Generated by Django 5.1.15 on 2026-09-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('subtitle', models.CharField(blank=True, default='', max_length=500, verbose_name='Quyi sarlavha')),
                ('badge', models.CharField(blank=True, default='', max_length=100, verbose_name='Badge')),
                ('icon', models.CharField(blank=True, default='Building2', max_length=100, verbose_name='Icon')),
                ('link', models.CharField(blank=True, default='/catalog', max_length=255, verbose_name='Havola')),
                ('product_ids', models.JSONField(blank=True, default=list, verbose_name='Mahsulotlar ID lari')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bosh sahifa bo‘limi',
                'verbose_name_plural': 'Bosh sahifa bo‘limlari',
                'ordering': ['order', 'id'],
            },
        ),
    ]
