# Generated by Django 5.1.15 on 2026-09-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_showcasesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='badge',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='btn_link',
            field=models.CharField(blank=True, default='/catalog', max_length=255, verbose_name='Tugma havolasi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='btn_text',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.CharField(default='/banners/banner-clean-promo.png', max_length=500, verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, default='Banner', max_length=255, verbose_name='Sarlavha'),
        ),
    ]
