# Generated by Django 5.1.15 on 2026-09-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_alter_banner_badge_alter_banner_btn_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('logo', models.CharField(blank=True, default='', max_length=500, verbose_name='Logo URL')),
                ('category', models.CharField(blank=True, default='', max_length=255, verbose_name='Kategoriya')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hamkor',
                'verbose_name_plural': 'Hamkorlar',
                'ordering': ['order', 'id'],
            },
        ),
    ]
