# Generated by Django 5.1.15 on 2026-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.TextField(default='/banners/banner-clean-promo.png', verbose_name='Rasm URL'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.TextField(blank=True, default='', verbose_name='Logo URL'),
        ),
    ]
