# Generated by Django 5.1.15 on 2026-09-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_alter_banner_image_alter_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcasesection',
            name='subtitle_ru',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Quyi sarlavha (RU)'),
        ),
        migrations.AddField(
            model_name='showcasesection',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha (RU)'),
        ),
    ]
