# Generated by Django 5.1.15 on 2026-09-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0008_update_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='badge_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Badge (RU)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='btn_text_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Tugma matni (RU)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (RU)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_alt_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Rasm tavsifi (RU)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_ru',
            field=models.TextField(blank=True, default='', verbose_name='Rasm URL (RU)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Sarlavha (RU)'),
        ),
    ]
