# Generated by Django 5.1.15 on 2026-10-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_banner_badge_ru_banner_btn_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Telegram Chat ID'),
        ),
    ]
